version: '3'
services:
  ldl:
    build: .
    working_dir: /home/ywz #path in container
    ipc: host
    #(path/ports in host: path/ports in container)
    volumes:
      - /home/ywz:/media
      - /home/ywz/test/mybackup:/home/ywz/mybackup
      - /home/ywz/test/mybackup:/root/mybackup
      - /home2/ywz/database:/home/ywz/database
    # ports:
    #   - "8000:8000"